### ISSUE TITLE
os.detected.classifier not properly evaluated during gradle build.

### ISSUE THREAD

**Issue by ydorego** [microbean/microbean-helm#144]
I have the following compile dependency in my gradle file: 'org.microbean:microbean-helm:2.8.2.1.0.4'. The build works without any issues when running gradle within Eclipse.

When the build is invoke from the command line (Gradle Version 4.1) I have the following errors:

    Errors occurred while build effective model from /Users/yvdorego/.gradle/caches/modules-2/files-2.1/org.microbean/microbean-helm/2.8.2.1.0.4/44fb98754ff742b4a237718238bd9cced7906ffd/microbean-helm-2.8.2.1.0.4.pom:
        'build.resources.resource.directory' is missing. in org.microbean:microbean-helm:2.8.2.1.0.4
    Errors occurred while build effective model from /Users/yvdorego/.gradle/caches/modules-2/files-2.1/org.microbean/microbean-development-annotations/0.1.3/abaddafbff41cfff5f9332014aa30a7506498e6d/microbean-development-annotations-0.1.3.pom:
        'build.resources.resource.directory' is missing. in org.microbean:microbean-development-annotations:0.1.3
    Errors occurred while build effective model from /Users/yvdorego/.gradle/caches/modules-2/files-2.1/org.microbean/microbean-kubernetes/0.1.1/7fdace2d7ffa0c5e56e9f588ecc632a6333fe655/microbean-kubernetes-0.1.1.pom:
        'build.resources.resource.directory' is missing. in org.microbean:microbean-kubernetes:0.1.1
    
    
    FAILURE: Build failed with an exception.
    
    > Could not find netty-tcnative-boringssl-static-${os.detected.classifier}.jar (io.netty:netty-tcnative-boringssl-static:2.0.6.Final).
      Searched in the following locations:
          https://repo1.maven.org/maven2/io/netty/netty-tcnative-boringssl-static/2.0.6.Final/netty-tcnative-boringssl-static-2.0.6.Final-${os.detected.classifier}.jar

As per above the `os.detected.classifier` is not being resolved.

Any help will be greatly appreciated

**Comment by ljnelson** [comment]
Hello; thanks for using microBean Helm.  You need a [build extension](https://github.com/trustin/os-maven-plugin#enabling-os-maven-plugin-on-your-maven-project).

**Comment by ljnelson** [comment]
Oh, sorry; I see you're using Gradle.  I'm not sure how to enable a Maven extension in Gradle, or how Gradle works with dependencies like this.

**Comment by ljnelson** [comment]
Oh, and there it is: https://github.com/trustin/os-maven-plugin#using-gradle

**Comment by ljnelson** [comment]
Closing; instructions are here: https://github.com/google/osdetector-gradle-plugin#usage

**Comment by ydorego** [comment]
Same error in my case too. My project has been put on the back burner, so I am no longer actively using microbean

**Comment by ljnelson** [comment]
I'd like to further understand this problem.

microBean Helm is a Maven project.  It uses the [`os-maven-plugin`](https://github.com/trustin/os-maven-plugin) during its build.

The `os-maven-plugin` installs itself into the current Maven build, determines the operating system, and sets several Maven properties early on in the Maven build lifecycle.  This allows you to build microBean Helm on a given platform and to download the [proper native library that is needed by the gRPC plumbing](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22io.netty%22%20AND%20a%3A%22netty-tcnative-boringssl-static%22).  If you [look on search.maven.org under the right coordinates](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22io.netty%22%20AND%20a%3A%22netty-tcnative-boringssl-static%22), you'll see that in the rightmost column there are downloads for macOS, Windows, Linux, etc.

The problem you are having is as a consumer of the [project object model (`pom.xml`) of _this_ project as it appears in Maven central](http://search.maven.org/#artifactdetails%7Corg.microbean%7Cmicrobean-helm%7C2.8.2.1.0.6%7Cjar).  Specifically, that `pom.xml` has a dependency on the netty-tcnative-boringssl-static artifact, and, further, on a particular instance of that artifact that is suited for the operating system you're running on.

Your problem seems to be that Gradle, out of the box, doesn't know anything about Maven plugins (specifically the `os-maven-plugin`).  Consequently, when Gradle is reading microBean Helm's `pom.xml` file and finds that it needs to download the artifact represented by the following coordinates:

    <groupId>io.netty</groupId>
    <artifactId>netty-tcnative-boringssl-static</artifactId>
    <version>2.0.6.Final</version>
    <type>jar</type>
    <classifier>${os.detected.classifier}</classifier>

…it doesn't know what to do because `${os.detected.classifier}` doesn't match any of the classifiers for the `io.netty:netty-tcnative-boringssl-static:2.0.6.Final:jar` artifact.  (Obviously.)

Many projects use the `os-maven-plugin`, so this is a general problem.

It looks like the good folks at Google ran into this problem at some point, and wrote a Gradle plugin that wraps the Maven `os-maven-plugin`.  [As documented](https://github.com/google/osdetector-gradle-plugin#usage), you should be able to install this in your Gradle build and the very same properties should be set at some equally early point in your Gradle build's lifecycle.

It's my understanding that this should resolve the problem: your Gradle installation will read in the `pom.xml` in order to figure out what `<dependency>` elements it contains, and, while reading it and building up its in-memory representation of it, will expand that `${os.detected.classifier}` property.

If this is _not_ what's happening, I'd find that very surprising.

Nevertheless, if it's not happening, then you'll need—using Gradle constructs—to exclude the `io.netty:netty-tcnative-boringssl-static:2.0.6.Final:jar` from your transitive dependency graph, and include the properly classified dependency (suitable for the operating system you're running on) by hand.

**Comment by OmkarBi** [comment]
@ljnelson yes second piece is not happening >>> "It's my understanding that this should resolve the problem: your Gradle installation will read in the pom.xml in order to figure out what <dependency> elements it contains, and, while reading it and building up its in-memory representation of it, will expand that ${os.detected.classifier} property.
If this is not what's happening, I'd find that very surprising."

My assumption is because for gradle pluging the variable name is osdetector.classifier vs os.detected.classifier in maven pluging (duh..)  and although your pom has the plugin looks like gradle build does not account for it when building.

!!!RESOLUTION  >>
@ydorego I was able to bypass it by Explicitly adding osdetectorplugin and io.netty:netty-tcnative-boringssl-static:2.0.6.Final:' + osdetector.classifier dependancy
then exclude group: 'io.netty', module: 'netty-tcnative-boringssl-static' for org.microbean:microbean-helm:2.8.2.1.0.5 dependency

`	
compile('io.netty:netty-tcnative-boringssl-static:2.0.6.Final:' + osdetector.classifier)
compile('org.microbean:microbean-helm:2.8.2.1.0.5') {
		exclude group: 'io.netty', module: 'netty-tcnative-boringssl-static'
	}
`

I think issue can be closed with above resolution

**Comment by ljnelson** [comment]
You write:

> My assumption is because for gradle pluging the variable name is osdetector.classifier vs os.detected.classifier in maven pluging (duh..) and although your pom has the plugin looks like gradle build does not account for it when building.

Just to be clear: _your Gradle file_ will need to have the Gradle plugin.  If your Gradle file that is masterminding your build has that plugin, you're saying that even then microBean Helm's transitive OS-specific dependencies cannot be resolved?

I'm glad the exclusion mechanism allowed you to work around the issue.  I'm going to leave it open until I figure out how this all works, so I can file issues against either the `os-maven-plugin`, the equivalent Gradle plugin, or both.

**Comment by OmkarBi** [comment]
yes I did include gradle plugin and that how my dependacy worked (injected osdetector.classifier)
`compile('io.netty:netty-tcnative-boringssl-static:2.0.6.Final:' + osdetector.classifier) `

**Comment by ttt307307** [comment]
1. https://github.com/google/osdetector-gradle-plugin#usage
```
apply plugin: 'com.google.osdetector'
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.google.gradle:osdetector-gradle-plugin:1.6.0'
    }
}
```

2.exclude and  then compile

```
    compile('io.netty:netty-tcnative:1.1.33.Fork22:' + osdetector.classifier)
    compile group: 'org.apache.rocketmq', name: 'rocketmq-client', version: '4.2.0'
    compile (group: 'org.apache.rocketmq', name: 'rocketmq-common', version: '4.2.0') {
        exclude group: 'io.netty', module: 'netty-tcnative'
    }
```

**Comment by ljnelson** [comment]
Closing; think we all understand the root issue here.  Thanks again for your input.

**Comment by seglo** [comment]
Just an FYI this is breaking SBT builds too.  I worked around by explicitly referencing the dependency as was suggested.

Ex)

```
libraryDependencies ++= Seq(
  "io.netty" % "netty-tcnative-boringssl-static" % "2.0.6.Final",
  "org.microbean" % "microbean-helm" % "2.8.2.1.1.0" exclude("io.netty", "netty-tcnative-boringssl-static")
)
```

**Comment by gabfssilva** [comment]
This should be documented.
