### ISSUE TITLE
Troubles with value overrides

### ISSUE THREAD

**Issue by frosenberg** [microbean/microbean-helm#78]
Thanks for providing this library. 

I tried the following example code: 

```java
package com.braintribe.cloud.TillerTest;

import java.net.URI;
import java.net.URL;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.Future;

import org.microbean.helm.ReleaseManager;
import org.microbean.helm.Tiller;
import org.microbean.helm.chart.URLChartLoader;

import hapi.chart.ChartOuterClass.Chart;
import hapi.chart.ConfigOuterClass;
import hapi.chart.ConfigOuterClass.Value;
import hapi.chart.ConfigOuterClass.Value.Builder;
import hapi.release.ReleaseOuterClass.Release;
import hapi.services.tiller.Tiller.InstallReleaseRequest;
import hapi.services.tiller.Tiller.InstallReleaseResponse;
import io.fabric8.kubernetes.client.DefaultKubernetesClient;

public class App {

	public static void main(String[] args) throws Exception {
		
		final URI uri = URI.create("https://kubernetes-charts.storage.googleapis.com/wordpress-0.6.6.tgz");
		assert uri != null;
		URL url = uri.toURL();
		Chart.Builder chart = null;
		try (final URLChartLoader chartLoader = new URLChartLoader()) {
			chart = chartLoader.load(url);
		}
		assert chart != null;

		try (final DefaultKubernetesClient client = new DefaultKubernetesClient();
				final Tiller tiller = new Tiller(client);
				final ReleaseManager releaseManager = new ReleaseManager(tiller)) {

			final InstallReleaseRequest.Builder requestBuilder = InstallReleaseRequest.newBuilder();
			assert requestBuilder != null;
			requestBuilder.setTimeout(300L);
			requestBuilder.setName("wordpress-test"); // Set the Helm release name
			requestBuilder.setWait(false); // Wait for Pods to be ready
			requestBuilder.setNamespace("myNS");
			
			// map of all values we need to override			
			Map<String, Value> values = new HashMap<String, Value>();

			values.put("persistence.enabled", Value.newBuilder().setValue("false").build());			
			requestBuilder.getValuesBuilder().putAllValues(values);  // does not seem to have any effect
			
			final Future<InstallReleaseResponse> releaseFuture = releaseManager.install(requestBuilder, chart);
			assert releaseFuture != null;
			final Release release = releaseFuture.get().getRelease();
			assert release != null;
		}
	}
}

```

The overides don't seem to have any effect. Do you have a working sample? I could not find anything in the docs or unit that that would get me further.

**Comment by ljnelson** [comment]
Hi!  At a quick glance, it looks like you might be using a deprecated inner class in `hapi.chart.ConfigOuterClass`, namely `Value`.  For supplying values, you want to be using the [`Config`](https://microbean.github.io/microbean-helm/apidocs/hapi/chart/ConfigOuterClass.Config.html) class.  I don't have any control over any classes starting with `hapi.`; they're generated from the protocol buffers source code.

I'll see if I can get a sample or two up soon.  In the mean time, you want to be using the [`setValues`](https://microbean.github.io/microbean-helm/apidocs/hapi/services/tiller/Tiller.InstallReleaseRequest.Builder.html#setValues-hapi.chart.ConfigOuterClass.Config-) method on `InstallReleaseRequest.Builder`.

**Comment by ljnelson** [comment]
Additionally, although the classes involved may or may not be deprecated, I can tell you that on the Tiller side, Helm's server-side componentry grabs your values by calling [`ConfigOrBuilder.getRaw`](https://microbean.github.io/microbean-helm/apidocs/hapi/chart/ConfigOuterClass.ConfigOrBuilder.html#getRaw--), so it is best to set them using `setRaw(String)` in `Config.Builder`.

**Comment by frosenberg** [comment]
Thanks for your quick response. We debugged a little and ended up putting together yaml structure via Maps and the use SnakeYaml to dump it as string and use `setRaw` as you suggested. 

I found the issues to be here: 
https://github.com/microbean/microbean-helm/blob/08ce90edb0e2a69a69621bc0d2a2234119caa07e/src/main/java/org/microbean/helm/chart/Configs.java#L129

It just used `getRaw()` and checks if it is `null` or `""`. I think it should actually check the `values` map from the builder first, then the `raw` content.

**Comment by ljnelson** [comment]
I hear you, but I think I'm going to solve this via documentation.  All of helm itself does nothing but check the raw `struct` field when it needs to check for `null` or empty values, so I do it the same way, on purpose, for fidelity.  You don't run into this problem's analog with plain-Jane helm, because of course you supply values on the command line or via a file.

I'll do two things: I'll make sure that #79 is addressed with good sample code and documentation, and I'll re-verify with the Helm team that no other methods should be used to deal with chart values other than `getRaw` and `setRaw`.

**Comment by ljnelson** [comment]
Per the last item in my comment above: https://kubernetes.slack.com/archives/C51E88VDG/p1517254771000026

**Comment by ljnelson** [comment]
@frosenberg I am going to take a hybrid approach here.

First, the `Raw` property always trumps.  That means if I get a value from [`getRaw()`](https://microbean.github.io/microbean-helm/apidocs/hapi/chart/ConfigOuterClass.Config.Builder.html#getRaw--) it always wins.  Full stop.

What I'll do, however, is: if that returns `null` or an empty `String`, then I'll grab the (much more limited, for example, no nesting) `Map` of `String`-to-`Value` instances via [`getValuesMap()`](https://microbean.github.io/microbean-helm/apidocs/hapi/chart/ConfigOuterClass.Config.Builder.html#getValuesMap--), and will use that to set the raw YAML when I ship things over the wire to Tiller.

I think this should be the best of all worlds: since `getRaw()` trumps, backwards compatibility is preserved, but if you have simple value needs (since `getValuesMap()` can't handle non-scalar value overrides) then I'll respect the `getValuesMap()` method.

I myself will never write to that map, because Tiller will never read from that map, but I can use it as a way to build valid YAML using SnakeYaml as a convenience mechanism for at least as long as that `getValuesMap()` method is not deprecated.

Stand by shortly for a PR and a fix.

**Comment by ljnelson** [comment]
Addressed with #83.

**Comment by blublinsky** [comment]
First, thanks for a wonderful library
About the values. If I understand correctly, the only way to update values is to replace the raw content.
This can be easily generated using snakeYaml. Can you provide an example that overwrites a raw value content with one that I am creating regardless of how I do this and reflect this somehow in documentation.
The other option that I see is to read chart and store it locally. Then replace (programmatically) values.yaml, read chart back and submit. This will work as well, by I have not found a method for storing chart to the local disk. Am I missing this?

**Comment by ljnelson** [comment]
You may be interested in #79.

To read a chart, you want to use some variant of [`AbstractChartLoader`](https://microbean.github.io/microbean-helm/apidocs/org/microbean/helm/chart/AbstractChartLoader.html), such as [`DirectoryChartLoader`](https://microbean.github.io/microbean-helm/apidocs/org/microbean/helm/chart/DirectoryChartLoader.html) or [`URLChartLoader`](https://microbean.github.io/microbean-helm/apidocs/org/microbean/helm/chart/URLChartLoader.html).

To write a chart, you want to use some variant of [`AbstractChartWriter`](https://microbean.github.io/microbean-helm/apidocs/org/microbean/helm/chart/AbstractChartWriter.html), such as [`TapeArchiveChartWriter`](https://microbean.github.io/microbean-helm/apidocs/org/microbean/helm/chart/TapeArchiveChartWriter.html).
